-- Referencia de t_log_emails (estructura real, no recrear).
-- Columnas: id (AI), fecha, modulo_origen, codigo_plantilla,
-- destinatarios, asunto, estado, mensaje_servidor.
-- t_config_smtp ya existe; no recrear.
